/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeImpl */

#ifndef _Included_NativeImpl
#define _Included_NativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeImpl
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeImpl_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeImpl
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeImpl_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
